name: Build Docker Images

on:
  push:
    branches:
      - main
      - dev
      - demo
  pull_request:
    branches:
      - main
      - dev
      - demo
    types:
    - opened
    - ready_for_review
    - reopened
    - synchronize
  merge_group:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
        - name: Print branch name
          run: |
            echo "GITHUB_REF: ${{ github.ref}}"
            echo "GITHUB_REF: ${{ github.ref_name}}
            echo "GITHUB_EVENT_NAME: ${{ github.event_name}}"
            echo "GITHUB_HEAD_REF: ${{ github.head_ref}}
            echo "GITHUB_BASE_REF: ${{ github.base_ref}}
  docker-build:
    strategy:
      matrix:
        include:
          - app_name: rag-adminwebapp
            dockerfile: docker/Admin.Dockerfile
          - app_name: rag-backend
            dockerfile: docker/Backend.Dockerfile
          - app_name: rag-webapp
            dockerfile: docker/Frontend.Dockerfile
    uses: ./.github/workflows/build-docker.yml
    with:
      registry: ${{ github.event.workflow_run.head_branch == 'main' && 'fruoccopublic.azurecr.io' || 'cwydcontainerreg.azurecr.io'}}
      username: ${{ github.event.workflow_run.head_branch == 'main' && 'fruoccopublic' || 'cwydcontainerreg'}}
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      push: ${{ github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'dev' || github.event.workflow_run.head_branch == 'demo' }}
    secrets: inherit
